//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarketAutomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class DebtTransaction
    {
        public int Id { get; set; }
        public int debtorID { get; set; }
        public string debtorTitle { get; set; }
        public Nullable<int> paidAmount { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    }
}
